CREATE TABLE Pessoa (
    idPessoa SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(14) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE Funcionario (
    idFuncionario SERIAL PRIMARY KEY,
    idPessoa INT UNIQUE REFERENCES Pessoa(idPessoa) ON DELETE CASCADE
);

CREATE TABLE Professor (
    idProfessor SERIAL PRIMARY KEY,
    idPessoa INT UNIQUE REFERENCES Pessoa(idPessoa) ON DELETE CASCADE
);

CREATE TABLE Aluno (
    idAluno SERIAL PRIMARY KEY,
    idPessoa INT UNIQUE REFERENCES Pessoa(idPessoa) ON DELETE CASCADE
);

CREATE TABLE Curso (
    idCurso SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE Turma (
    idTurma SERIAL PRIMARY KEY,
    ano INT NOT NULL,
    idCurso INT REFERENCES Curso(idCurso) ON DELETE CASCADE
);

CREATE TABLE Matricula (
    idMatricula SERIAL PRIMARY KEY,
    idAluno INT REFERENCES Aluno(idAluno) ON DELETE CASCADE,
    idTurma INT REFERENCES Turma(idTurma) ON DELETE CASCADE,
    nota1 NUMERIC(4,2),
    nota2 NUMERIC(4,2)
);
